# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ESP301.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_ESP301(object):
    def setupUi(self, ESP301):
        ESP301.setObjectName("ESP301")
        ESP301.resize(691, 570)
        self.buttonBox = QtWidgets.QDialogButtonBox(ESP301)
        self.buttonBox.setGeometry(QtCore.QRect(440, 410, 91, 241))
        self.buttonBox.setOrientation(QtCore.Qt.Vertical)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Save)
        self.buttonBox.setObjectName("buttonBox")
        self.tabWidget = QtWidgets.QTabWidget(ESP301)
        self.tabWidget.setGeometry(QtCore.QRect(60, 80, 361, 381))
        self.tabWidget.setObjectName("tabWidget")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.checkBox = QtWidgets.QCheckBox(self.tab)
        self.checkBox.setGeometry(QtCore.QRect(40, 50, 70, 17))
        self.checkBox.setObjectName("checkBox")
        self.checkBox_2 = QtWidgets.QCheckBox(self.tab)
        self.checkBox_2.setGeometry(QtCore.QRect(40, 70, 111, 17))
        self.checkBox_2.setObjectName("checkBox_2")
        self.checkBox_3 = QtWidgets.QCheckBox(self.tab)
        self.checkBox_3.setGeometry(QtCore.QRect(40, 90, 111, 17))
        self.checkBox_3.setObjectName("checkBox_3")
        self.checkBox_4 = QtWidgets.QCheckBox(self.tab)
        self.checkBox_4.setGeometry(QtCore.QRect(40, 110, 131, 17))
        self.checkBox_4.setObjectName("checkBox_4")
        self.checkBox_5 = QtWidgets.QCheckBox(self.tab)
        self.checkBox_5.setGeometry(QtCore.QRect(40, 130, 221, 17))
        self.checkBox_5.setObjectName("checkBox_5")
        self.label = QtWidgets.QLabel(self.tab)
        self.label.setGeometry(QtCore.QRect(20, 20, 47, 13))
        self.label.setMaximumSize(QtCore.QSize(47, 16777215))
        self.label.setLineWidth(3)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.tab)
        self.label_2.setGeometry(QtCore.QRect(30, 180, 47, 13))
        self.label_2.setMaximumSize(QtCore.QSize(47, 16777215))
        self.label_2.setLineWidth(3)
        self.label_2.setObjectName("label_2")
        self.horizontalSlider = QtWidgets.QSlider(self.tab)
        self.horizontalSlider.setGeometry(QtCore.QRect(30, 230, 160, 22))
        self.horizontalSlider.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider.setObjectName("horizontalSlider")
        self.label_3 = QtWidgets.QLabel(self.tab)
        self.label_3.setGeometry(QtCore.QRect(30, 260, 16, 16))
        self.label_3.setMaximumSize(QtCore.QSize(47, 16777215))
        self.label_3.setLineWidth(3)
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.tab)
        self.label_4.setGeometry(QtCore.QRect(180, 250, 41, 20))
        self.label_4.setMaximumSize(QtCore.QSize(47, 16777215))
        self.label_4.setLineWidth(3)
        self.label_4.setObjectName("label_4")
        self.pushButton_2 = QtWidgets.QPushButton(self.tab)
        self.pushButton_2.setGeometry(QtCore.QRect(240, 310, 91, 23))
        self.pushButton_2.setObjectName("pushButton_2")
        self.tabWidget.addTab(self.tab, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.label_5 = QtWidgets.QLabel(self.tab_2)
        self.label_5.setGeometry(QtCore.QRect(30, 20, 47, 13))
        self.label_5.setMaximumSize(QtCore.QSize(47, 16777215))
        self.label_5.setLineWidth(3)
        self.label_5.setObjectName("label_5")
        self.checkBox_6 = QtWidgets.QCheckBox(self.tab_2)
        self.checkBox_6.setGeometry(QtCore.QRect(40, 40, 111, 17))
        self.checkBox_6.setObjectName("checkBox_6")
        self.checkBox_7 = QtWidgets.QCheckBox(self.tab_2)
        self.checkBox_7.setGeometry(QtCore.QRect(40, 60, 111, 17))
        self.checkBox_7.setObjectName("checkBox_7")
        self.checkBox_8 = QtWidgets.QCheckBox(self.tab_2)
        self.checkBox_8.setGeometry(QtCore.QRect(40, 80, 111, 17))
        self.checkBox_8.setObjectName("checkBox_8")
        self.checkBox_9 = QtWidgets.QCheckBox(self.tab_2)
        self.checkBox_9.setGeometry(QtCore.QRect(40, 100, 111, 17))
        self.checkBox_9.setObjectName("checkBox_9")
        self.checkBox_10 = QtWidgets.QCheckBox(self.tab_2)
        self.checkBox_10.setGeometry(QtCore.QRect(40, 120, 111, 17))
        self.checkBox_10.setObjectName("checkBox_10")
        self.checkBox_11 = QtWidgets.QCheckBox(self.tab_2)
        self.checkBox_11.setGeometry(QtCore.QRect(40, 140, 111, 17))
        self.checkBox_11.setObjectName("checkBox_11")
        self.checkBox_12 = QtWidgets.QCheckBox(self.tab_2)
        self.checkBox_12.setGeometry(QtCore.QRect(190, 40, 111, 17))
        self.checkBox_12.setObjectName("checkBox_12")
        self.checkBox_13 = QtWidgets.QCheckBox(self.tab_2)
        self.checkBox_13.setGeometry(QtCore.QRect(190, 60, 111, 17))
        self.checkBox_13.setObjectName("checkBox_13")
        self.checkBox_14 = QtWidgets.QCheckBox(self.tab_2)
        self.checkBox_14.setGeometry(QtCore.QRect(190, 80, 111, 17))
        self.checkBox_14.setObjectName("checkBox_14")
        self.checkBox_15 = QtWidgets.QCheckBox(self.tab_2)
        self.checkBox_15.setGeometry(QtCore.QRect(190, 100, 111, 17))
        self.checkBox_15.setObjectName("checkBox_15")
        self.checkBox_16 = QtWidgets.QCheckBox(self.tab_2)
        self.checkBox_16.setGeometry(QtCore.QRect(190, 120, 111, 17))
        self.checkBox_16.setObjectName("checkBox_16")
        self.checkBox_17 = QtWidgets.QCheckBox(self.tab_2)
        self.checkBox_17.setGeometry(QtCore.QRect(190, 140, 111, 17))
        self.checkBox_17.setObjectName("checkBox_17")
        self.label_6 = QtWidgets.QLabel(self.tab_2)
        self.label_6.setGeometry(QtCore.QRect(30, 190, 47, 13))
        self.label_6.setMaximumSize(QtCore.QSize(47, 16777215))
        self.label_6.setLineWidth(3)
        self.label_6.setObjectName("label_6")
        self.horizontalSlider_2 = QtWidgets.QSlider(self.tab_2)
        self.horizontalSlider_2.setGeometry(QtCore.QRect(30, 220, 160, 22))
        self.horizontalSlider_2.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider_2.setObjectName("horizontalSlider_2")
        self.label_7 = QtWidgets.QLabel(self.tab_2)
        self.label_7.setGeometry(QtCore.QRect(30, 250, 21, 20))
        self.label_7.setMaximumSize(QtCore.QSize(47, 16777215))
        self.label_7.setLineWidth(3)
        self.label_7.setObjectName("label_7")
        self.label_8 = QtWidgets.QLabel(self.tab_2)
        self.label_8.setGeometry(QtCore.QRect(180, 240, 47, 16))
        self.label_8.setMaximumSize(QtCore.QSize(47, 16777215))
        self.label_8.setLineWidth(3)
        self.label_8.setObjectName("label_8")
        self.pushButton_3 = QtWidgets.QPushButton(self.tab_2)
        self.pushButton_3.setGeometry(QtCore.QRect(240, 300, 91, 23))
        self.pushButton_3.setObjectName("pushButton_3")
        self.tabWidget.addTab(self.tab_2, "")
        self.tab_3 = QtWidgets.QWidget()
        self.tab_3.setObjectName("tab_3")
        self.checkBox_18 = QtWidgets.QCheckBox(self.tab_3)
        self.checkBox_18.setGeometry(QtCore.QRect(50, 50, 111, 17))
        self.checkBox_18.setObjectName("checkBox_18")
        self.checkBox_19 = QtWidgets.QCheckBox(self.tab_3)
        self.checkBox_19.setGeometry(QtCore.QRect(50, 70, 111, 17))
        self.checkBox_19.setObjectName("checkBox_19")
        self.label_9 = QtWidgets.QLabel(self.tab_3)
        self.label_9.setGeometry(QtCore.QRect(50, 20, 47, 13))
        self.label_9.setMaximumSize(QtCore.QSize(47, 16777215))
        self.label_9.setLineWidth(3)
        self.label_9.setObjectName("label_9")
        self.label_10 = QtWidgets.QLabel(self.tab_3)
        self.label_10.setGeometry(QtCore.QRect(50, 130, 47, 13))
        self.label_10.setMaximumSize(QtCore.QSize(47, 16777215))
        self.label_10.setLineWidth(3)
        self.label_10.setObjectName("label_10")
        self.horizontalSlider_3 = QtWidgets.QSlider(self.tab_3)
        self.horizontalSlider_3.setGeometry(QtCore.QRect(50, 170, 160, 22))
        self.horizontalSlider_3.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider_3.setObjectName("horizontalSlider_3")
        self.label_11 = QtWidgets.QLabel(self.tab_3)
        self.label_11.setGeometry(QtCore.QRect(50, 200, 21, 20))
        self.label_11.setMaximumSize(QtCore.QSize(47, 16777215))
        self.label_11.setLineWidth(3)
        self.label_11.setObjectName("label_11")
        self.label_12 = QtWidgets.QLabel(self.tab_3)
        self.label_12.setGeometry(QtCore.QRect(190, 200, 47, 16))
        self.label_12.setMaximumSize(QtCore.QSize(47, 16777215))
        self.label_12.setLineWidth(3)
        self.label_12.setObjectName("label_12")
        self.pushButton_4 = QtWidgets.QPushButton(self.tab_3)
        self.pushButton_4.setGeometry(QtCore.QRect(230, 280, 91, 23))
        self.pushButton_4.setObjectName("pushButton_4")
        self.tabWidget.addTab(self.tab_3, "")
        self.pushButton = QtWidgets.QPushButton(ESP301)
        self.pushButton.setGeometry(QtCore.QRect(440, 470, 91, 23))
        self.pushButton.setObjectName("pushButton")

        self.retranslateUi(ESP301)
        self.tabWidget.setCurrentIndex(1)
        self.buttonBox.accepted.connect(ESP301.accept)
        self.buttonBox.rejected.connect(ESP301.reject)
        QtCore.QMetaObject.connectSlotsByName(ESP301)

    def retranslateUi(self, ESP301):
        _translate = QtCore.QCoreApplication.translate
        ESP301.setWindowTitle(_translate("ESP301", "Dialog"))
        self.checkBox.setText(_translate("ESP301", "0 - Default"))
        self.checkBox_2.setText(_translate("ESP301", "1 - DC servo motor"))
        self.checkBox_3.setText(_translate("ESP301", "2 - step motor"))
        self.checkBox_4.setText(_translate("ESP301", "3 - commutated motor"))
        self.checkBox_5.setText(_translate("ESP301", "4 - commutated brushless DC servo motor"))
        self.label.setText(_translate("ESP301", "Range nn"))
        self.label_2.setText(_translate("ESP301", "Range xx"))
        self.label_3.setText(_translate("ESP301", "1"))
        self.label_4.setText(_translate("ESP301", "MAX "))
        self.pushButton_2.setText(_translate("ESP301", "Set to Default "))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("ESP301", "QM - Motor Type QM"))
        self.label_5.setText(_translate("ESP301", "Range nn"))
        self.checkBox_6.setText(_translate("ESP301", "0 - Encoder Count"))
        self.checkBox_7.setText(_translate("ESP301", "1 - Motor Step"))
        self.checkBox_8.setText(_translate("ESP301", "2 - Milimeter"))
        self.checkBox_9.setText(_translate("ESP301", "3 - Micrometer"))
        self.checkBox_10.setText(_translate("ESP301", "4 - Inches"))
        self.checkBox_11.setText(_translate("ESP301", "5 - Mili-inches"))
        self.checkBox_12.setText(_translate("ESP301", "6 - Micro-inches"))
        self.checkBox_13.setText(_translate("ESP301", "7 - Degree"))
        self.checkBox_14.setText(_translate("ESP301", "8 - Gradian"))
        self.checkBox_15.setText(_translate("ESP301", "9 - Radian"))
        self.checkBox_16.setText(_translate("ESP301", "10 - Miliradian"))
        self.checkBox_17.setText(_translate("ESP301", "11 - Microradian"))
        self.label_6.setText(_translate("ESP301", "Range xx"))
        self.label_7.setText(_translate("ESP301", "1"))
        self.label_8.setText(_translate("ESP301", "MAX "))
        self.pushButton_3.setText(_translate("ESP301", "Set to Default "))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("ESP301", "SN - Axis Displacement Units"))
        self.checkBox_18.setText(_translate("ESP301", "1 - 250"))
        self.checkBox_19.setText(_translate("ESP301", "1 - 1000"))
        self.label_9.setText(_translate("ESP301", "Range nn"))
        self.label_10.setText(_translate("ESP301", "Range xx"))
        self.label_11.setText(_translate("ESP301", "1"))
        self.label_12.setText(_translate("ESP301", "MAX "))
        self.pushButton_4.setText(_translate("ESP301", "Set to Default "))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_3), _translate("ESP301", "Microstep Factor"))
        self.pushButton.setText(_translate("ESP301", "Set to Default "))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    ESP301 = QtWidgets.QDialog()
    ui = Ui_ESP301()
    ui.setupUi(ESP301)
    ESP301.show()
    sys.exit(app.exec_())

