## ESP301

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_ESP301(object):
    def setupUi3(self, ESP301):
        ESP301.setObjectName("ESP301")
        ESP301.resize(691, 570)
        self.buttonBox = QtWidgets.QDialogButtonBox(ESP301)
        self.buttonBox.setGeometry(QtCore.QRect(580, 480, 91, 241))
        self.buttonBox.setOrientation(QtCore.Qt.Vertical)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Save)
        self.buttonBox.setObjectName("buttonBox")
        self.tabWidget = QtWidgets.QTabWidget(ESP301)
        self.tabWidget.setGeometry(QtCore.QRect(50, 50, 511, 441))
        self.tabWidget.setObjectName("tabWidget")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.pushButton_2 = QtWidgets.QPushButton(self.tab)
        self.pushButton_2.setGeometry(QtCore.QRect(370, 340, 91, 21))
        self.pushButton_2.setObjectName("pushButton_2")
        self.radioButton_2 = QtWidgets.QRadioButton(self.tab)
        self.radioButton_2.setGeometry(QtCore.QRect(40, 40, 82, 17))
        self.radioButton_2.setObjectName("radioButton_2")
        self.radioButton_3 = QtWidgets.QRadioButton(self.tab)
        self.radioButton_3.setGeometry(QtCore.QRect(40, 120, 101, 17))
        self.radioButton_3.setObjectName("radioButton_3")
        self.radioButton_4 = QtWidgets.QRadioButton(self.tab)
        self.radioButton_4.setGeometry(QtCore.QRect(40, 150, 82, 17))
        self.radioButton_4.setObjectName("radioButton_4")
        self.radioButton_5 = QtWidgets.QRadioButton(self.tab)
        self.radioButton_5.setGeometry(QtCore.QRect(190, 120, 131, 17))
        self.radioButton_5.setObjectName("radioButton_5")
        self.radioButton_6 = QtWidgets.QRadioButton(self.tab)
        self.radioButton_6.setGeometry(QtCore.QRect(190, 150, 221, 17))
        self.radioButton_6.setObjectName("radioButton_6")
        self.tabWidget.addTab(self.tab, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.checkBox_6 = QtWidgets.QCheckBox(self.tab_2)
        self.checkBox_6.setGeometry(QtCore.QRect(40, 40, 111, 17))
        self.checkBox_6.setObjectName("checkBox_6")
        self.checkBox_7 = QtWidgets.QCheckBox(self.tab_2)
        self.checkBox_7.setGeometry(QtCore.QRect(40, 60, 111, 17))
        self.checkBox_7.setObjectName("checkBox_7")
        self.checkBox_8 = QtWidgets.QCheckBox(self.tab_2)
        self.checkBox_8.setGeometry(QtCore.QRect(40, 80, 111, 17))
        self.checkBox_8.setObjectName("checkBox_8")
        self.checkBox_9 = QtWidgets.QCheckBox(self.tab_2)
        self.checkBox_9.setGeometry(QtCore.QRect(40, 100, 111, 17))
        self.checkBox_9.setObjectName("checkBox_9")
        self.checkBox_10 = QtWidgets.QCheckBox(self.tab_2)
        self.checkBox_10.setGeometry(QtCore.QRect(40, 120, 111, 17))
        self.checkBox_10.setObjectName("checkBox_10")
        self.checkBox_11 = QtWidgets.QCheckBox(self.tab_2)
        self.checkBox_11.setGeometry(QtCore.QRect(40, 140, 111, 17))
        self.checkBox_11.setObjectName("checkBox_11")
        self.checkBox_12 = QtWidgets.QCheckBox(self.tab_2)
        self.checkBox_12.setGeometry(QtCore.QRect(190, 40, 111, 17))
        self.checkBox_12.setObjectName("checkBox_12")
        self.checkBox_13 = QtWidgets.QCheckBox(self.tab_2)
        self.checkBox_13.setGeometry(QtCore.QRect(190, 60, 111, 17))
        self.checkBox_13.setObjectName("checkBox_13")
        self.checkBox_14 = QtWidgets.QCheckBox(self.tab_2)
        self.checkBox_14.setGeometry(QtCore.QRect(190, 80, 111, 17))
        self.checkBox_14.setObjectName("checkBox_14")
        self.checkBox_15 = QtWidgets.QCheckBox(self.tab_2)
        self.checkBox_15.setGeometry(QtCore.QRect(190, 100, 111, 17))
        self.checkBox_15.setObjectName("checkBox_15")
        self.checkBox_16 = QtWidgets.QCheckBox(self.tab_2)
        self.checkBox_16.setGeometry(QtCore.QRect(190, 120, 111, 17))
        self.checkBox_16.setObjectName("checkBox_16")
        self.checkBox_17 = QtWidgets.QCheckBox(self.tab_2)
        self.checkBox_17.setGeometry(QtCore.QRect(190, 140, 111, 17))
        self.checkBox_17.setObjectName("checkBox_17")
        self.pushButton_3 = QtWidgets.QPushButton(self.tab_2)
        self.pushButton_3.setGeometry(QtCore.QRect(240, 300, 91, 23))
        self.pushButton_3.setObjectName("pushButton_3")
        self.tabWidget.addTab(self.tab_2, "")
        self.tab_3 = QtWidgets.QWidget()
        self.tab_3.setObjectName("tab_3")
        self.checkBox_18 = QtWidgets.QCheckBox(self.tab_3)
        self.checkBox_18.setGeometry(QtCore.QRect(50, 50, 111, 17))
        self.checkBox_18.setObjectName("checkBox_18")
        self.checkBox_19 = QtWidgets.QCheckBox(self.tab_3)
        self.checkBox_19.setGeometry(QtCore.QRect(50, 70, 111, 17))
        self.checkBox_19.setObjectName("checkBox_19")
        self.pushButton_4 = QtWidgets.QPushButton(self.tab_3)
        self.pushButton_4.setGeometry(QtCore.QRect(230, 280, 91, 23))
        self.pushButton_4.setObjectName("pushButton_4")
        self.tabWidget.addTab(self.tab_3, "")
        self.tab_4 = QtWidgets.QWidget()
        self.tab_4.setObjectName("tab_4")
        self.label = QtWidgets.QLabel(self.tab_4)
        self.label.setGeometry(QtCore.QRect(80, 40, 131, 16))
        self.label.setObjectName("label")
        self.comboBox = QtWidgets.QComboBox(self.tab_4)
        self.comboBox.setGeometry(QtCore.QRect(80, 70, 69, 22))
        self.comboBox.setObjectName("comboBox")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.pushButton_5 = QtWidgets.QPushButton(self.tab_4)
        self.pushButton_5.setGeometry(QtCore.QRect(350, 330, 91, 23))
        self.pushButton_5.setObjectName("pushButton_5")
        self.tabWidget.addTab(self.tab_4, "")
        self.tab_5 = QtWidgets.QWidget()
        self.tab_5.setObjectName("tab_5")
        self.label_2 = QtWidgets.QLabel(self.tab_5)
        self.label_2.setGeometry(QtCore.QRect(180, 170, 47, 13))
        self.label_2.setObjectName("label_2")
        self.tabWidget.addTab(self.tab_5, "")
        self.tab_6 = QtWidgets.QWidget()
        self.tab_6.setObjectName("tab_6")
        self.label_3 = QtWidgets.QLabel(self.tab_6)
        self.label_3.setGeometry(QtCore.QRect(190, 160, 47, 13))
        self.label_3.setObjectName("label_3")
        self.tabWidget.addTab(self.tab_6, "")
        self.tab_7 = QtWidgets.QWidget()
        self.tab_7.setObjectName("tab_7")
        self.label_4 = QtWidgets.QLabel(self.tab_7)
        self.label_4.setGeometry(QtCore.QRect(60, 50, 301, 21))
        self.label_4.setObjectName("label_4")
        self.lineEdit_2 = QtWidgets.QLineEdit(self.tab_7)
        self.lineEdit_2.setGeometry(QtCore.QRect(60, 80, 111, 20))
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.pushButton_6 = QtWidgets.QPushButton(self.tab_7)
        self.pushButton_6.setGeometry(QtCore.QRect(360, 350, 91, 23))
        self.pushButton_6.setObjectName("pushButton_6")
        self.tabWidget.addTab(self.tab_7, "")
        self.tab_8 = QtWidgets.QWidget()
        self.tab_8.setObjectName("tab_8")
        self.label_5 = QtWidgets.QLabel(self.tab_8)
        self.label_5.setGeometry(QtCore.QRect(40, 50, 301, 21))
        self.label_5.setObjectName("label_5")
        self.lineEdit_3 = QtWidgets.QLineEdit(self.tab_8)
        self.lineEdit_3.setGeometry(QtCore.QRect(40, 80, 111, 20))
        self.lineEdit_3.setObjectName("lineEdit_3")
        self.pushButton_7 = QtWidgets.QPushButton(self.tab_8)
        self.pushButton_7.setGeometry(QtCore.QRect(340, 280, 91, 23))
        self.pushButton_7.setObjectName("pushButton_7")
        self.tabWidget.addTab(self.tab_8, "")
        self.tab_9 = QtWidgets.QWidget()
        self.tab_9.setObjectName("tab_9")
        self.lineEdit_4 = QtWidgets.QLineEdit(self.tab_9)
        self.lineEdit_4.setGeometry(QtCore.QRect(40, 80, 111, 20))
        self.lineEdit_4.setObjectName("lineEdit_4")
        self.label_6 = QtWidgets.QLabel(self.tab_9)
        self.label_6.setGeometry(QtCore.QRect(40, 50, 301, 21))
        self.label_6.setObjectName("label_6")
        self.pushButton_8 = QtWidgets.QPushButton(self.tab_9)
        self.pushButton_8.setGeometry(QtCore.QRect(370, 270, 91, 23))
        self.pushButton_8.setObjectName("pushButton_8")
        self.tabWidget.addTab(self.tab_9, "")
        self.pushButton = QtWidgets.QPushButton(ESP301)
        self.pushButton.setGeometry(QtCore.QRect(570, 400, 101, 23))
        self.pushButton.setObjectName("pushButton")

        self.retranslateUi(ESP301)
        self.tabWidget.setCurrentIndex(4)
        self.buttonBox.accepted.connect(ESP301.accept)
        self.buttonBox.rejected.connect(ESP301.reject)
        QtCore.QMetaObject.connectSlotsByName(ESP301)

    def retranslateUi(self, ESP301):
        _translate = QtCore.QCoreApplication.translate
        ESP301.setWindowTitle(_translate("ESP301", "Dialog"))
        self.pushButton_2.setText(_translate("ESP301", "Set to Default "))
        self.radioButton_2.setText(_translate("ESP301", "Default"))
        self.radioButton_3.setText(_translate("ESP301", "DC servo motor"))
        self.radioButton_4.setText(_translate("ESP301", "step motor"))
        self.radioButton_5.setText(_translate("ESP301", "commutated motor"))
        self.radioButton_6.setText(_translate("ESP301", "commutated brushless DC servo motor"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("ESP301", "Motor Type "))
        self.checkBox_6.setText(_translate("ESP301", "Encoder Count"))
        self.checkBox_7.setText(_translate("ESP301", "Motor Step"))
        self.checkBox_8.setText(_translate("ESP301", "Milimeter"))
        self.checkBox_9.setText(_translate("ESP301", "Micrometer"))
        self.checkBox_10.setText(_translate("ESP301", "Inches"))
        self.checkBox_11.setText(_translate("ESP301", "Mili-inches"))
        self.checkBox_12.setText(_translate("ESP301", "Micro-inches"))
        self.checkBox_13.setText(_translate("ESP301", "Degree"))
        self.checkBox_14.setText(_translate("ESP301", "Gradian"))
        self.checkBox_15.setText(_translate("ESP301", "Radian"))
        self.checkBox_16.setText(_translate("ESP301", "Miliradian"))
        self.checkBox_17.setText(_translate("ESP301", "Microradian"))
        self.pushButton_3.setText(_translate("ESP301", "Set to Default "))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("ESP301", "Axis Displacement Units"))
        self.checkBox_18.setText(_translate("ESP301", "1 - 250"))
        self.checkBox_19.setText(_translate("ESP301", "1 - 1000"))
        self.pushButton_4.setText(_translate("ESP301", "Set to Default "))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_3), _translate("ESP301", "Microstep Factor"))
        self.label.setText(_translate("ESP301", "Set Position Resolution"))
        self.comboBox.setItemText(0, _translate("ESP301", "0"))
        self.comboBox.setItemText(1, _translate("ESP301", "1"))
        self.comboBox.setItemText(2, _translate("ESP301", "2"))
        self.comboBox.setItemText(3, _translate("ESP301", "3"))
        self.comboBox.setItemText(4, _translate("ESP301", "4"))
        self.comboBox.setItemText(5, _translate("ESP301", "5"))
        self.comboBox.setItemText(6, _translate("ESP301", "6"))
        self.comboBox.setItemText(7, _translate("ESP301", "7"))
        self.pushButton_5.setText(_translate("ESP301", "Set to Default "))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_4), _translate("ESP301", "Position Display Resolution"))
        self.label_2.setText(_translate("ESP301", "To define"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_5), _translate("ESP301", "Feedback Configuration"))
        self.label_3.setText(_translate("ESP301", "To define"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_6), _translate("ESP301", "Amplifier I/0 Configuration"))
        self.label_4.setText(_translate("ESP301", "Insert number in range \'2e-9\', \'2e9\' or \'?\' for present setting"))
        self.pushButton_6.setText(_translate("ESP301", "Set to Default "))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_7), _translate("ESP301", "Encoder Resolution"))
        self.label_5.setText(_translate("ESP301", "Set average motor voltage output"))
        self.pushButton_7.setText(_translate("ESP301", "Set to Default "))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_8), _translate("ESP301", "Average Motor Voltage"))
        self.label_6.setText(_translate("ESP301", "Insert number in range \'2e-9\', \'2e9\' or \'?\' for present setting"))
        self.pushButton_8.setText(_translate("ESP301", "Set to Default "))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_9), _translate("ESP301", "Maximum Acceleration_Deceleration"))
        self.pushButton.setText(_translate("ESP301", "Set All to Default "))



if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    ESP301_1 = QtWidgets.QDialog()
    ui3 = Ui_ESP301()
    ui3.setupUi3(ESP301_1)
    ESP301_1.show()
    sys.exit(app.exec_())